# Generated by Django 4.2 on 2024-12-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_audiofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
