# Generated by Django 4.2 on 2024-12-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_audiofile_likes'),
        ('myapp', '0004_alter_item_description_alter_item_name'),
    ]

    operations = [
    ]
